// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzDNN4tm9QWnaAawWtyPbk3tQXaqw7bOY',
    appId: '1:188425765765:web:b56e4c66868b6d361a7aec',
    messagingSenderId: '188425765765',
    projectId: 'fire-base-flutter-8f55b',
    authDomain: 'fire-base-flutter-8f55b.firebaseapp.com',
    storageBucket: 'fire-base-flutter-8f55b.firebasestorage.app',
    measurementId: 'G-25D2BB256S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDakRENrwjWc0aQOlf1VNqFrD4XA8iJPSs',
    appId: '1:188425765765:android:ff90209fc97810b61a7aec',
    messagingSenderId: '188425765765',
    projectId: 'fire-base-flutter-8f55b',
    storageBucket: 'fire-base-flutter-8f55b.firebasestorage.app',
  );
}
